title: Manikanta reddy chamala
logo: /assets/img/(https://github.com/manikantareddychamala/Mani.Portfolio/assets/162694056/18f3bec3-7f07-4adc-8433-6235429d4e14)
<h1 align="center">Hi 👋, I'm Manikanta reddy chamala</h1>
description: text below image
show_downloads: true
theme: jekyll-theme-minimal
